"""Regenerate the Swift Russian catalogue from the Python one.

    python3 apple/Tools/generate_russian_catalogue.py

`src/binaural/locales/ru.py` is the single source of truth for Russian text
(CONTRACT rule 3). This script parses it with the Python AST — so implicit
string concatenation is resolved exactly the way `i18n.tr` sees it — and writes
`apple/Sources/Core/Locales/RussianCatalogue.swift` with the same keys, the same
order and the same section comments.

It reads the Python package and writes only into `apple/`.
"""

from __future__ import annotations

import ast
import io
import re
import sys
import tokenize
from pathlib import Path

HEADER = '''import Foundation

/// The Russian catalogue: English source string -> Russian text.
///
/// Verbatim port of `src/binaural/locales/ru.py` (`MESSAGES`). The keys are the
/// English source strings exactly as they are passed to ``L10n/tr(_:_:)``, which is
/// what makes a missing key degrade to English instead of to an empty label.
///
/// Generated by `apple/Tools/generate_russian_catalogue.py` from the Python AST
/// (implicit string concatenation already resolved by the parser) and ordered like
/// the Python dictionary, section comments included. `L10nTests` re-reads `ru.py` at
/// test time and asserts the *key sets* are equal, so an edit to `ru.py` that this
/// file has not absorbed fails the suite instead of quietly dropping Russian text.
///
/// Style follows `ru.py`: calm and factual, no marketing and no medical promises
/// (SPEC §6.13 - the app is not a medical device). Placeholders (`%1`, `{name}`) are
/// kept verbatim: only the surrounding wording is translated.
public enum RussianCatalogue {

    /// Every Russian message, keyed by its English source string.
    public static let messages: [String: String] = [
'''


def swift_literal(text: str) -> str:
    out = ['"']
    for ch in text:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def in_additions(source: str) -> str:
    """The body of `RussianWindowAdditions.messages`, comments and all.

    Everything up to the closing brace of the dictionary literal, so the keys can be read
    without parsing Swift properly — the same job `L10nTests` does with a substring scan.
    """
    start = source.index("static let messages")
    # `[String: String]` in the annotation is also a `[`, so start from the literal's own.
    open_brace = source.index("=", start)
    open_brace = source.index("[", open_brace)
    depth = 0
    for index in range(open_brace, len(source)):
        if source[index] == "[":
            depth += 1
        elif source[index] == "]":
            depth -= 1
            if depth == 0:
                return source[open_brace:index + 1]
    raise SystemExit("RussianWindowAdditions.messages: dictionary literal not closed")


def swift_keys(literal: str) -> list[str]:
    """The keys of a Swift `[String: String]` literal.

    A scan, not a parser: the keys are always the first string literal of an entry, and
    this only has to notice the duplicates a hand-maintained file accumulates.
    """
    keys: list[str] = []
    for match in re.finditer(r'"(?:[^"\\]|\\.)*"(?=\s*:)', literal):
        keys.append(swift_unescape(match.group(0)[1:-1]))
    return keys


def swift_unescape(text: str) -> str:
    out: list[str] = []
    index = 0
    while index < len(text):
        character = text[index]
        if character != "\\" or index + 1 >= len(text):
            out.append(character)
            index += 1
            continue
        escaped = text[index + 1]
        if escaped == "u" and text[index + 2:index + 3] == "{":
            close = text.index("}", index)
            out.append(chr(int(text[index + 3:close], 16)))
            index = close + 1
            continue
        out.append({"n": "\n", "t": "\t", "r": "\r"}.get(escaped, escaped))
        index += 2
    return "".join(out)


def messages_node(tree: ast.AST) -> ast.Dict:
    """The `MESSAGES` dict literal of the catalogue module."""
    for node in ast.walk(tree):
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", "") == "MESSAGES":
            assert isinstance(node.value, ast.Dict)
            return node.value
    raise SystemExit("MESSAGES not found")


def comments_by_line(source: str) -> dict[int, str]:
    """The comment block that documents the first code token after it."""
    blocks: dict[int, str] = {}
    pending: list[str] = []
    for tok in tokenize.generate_tokens(io.StringIO(source).readline):
        if tok.type == tokenize.COMMENT:
            body = tok.string.lstrip("#").strip()
            if not body:
                pending = []
            elif body.startswith("---") and body.endswith("---"):
                # A section header: the dashes are decoration, the text is the title.
                pending = [body.strip("- ").strip()]
            else:
                pending.append(body)
        elif tok.type in (
            tokenize.NL,
            tokenize.NEWLINE,
            tokenize.INDENT,
            tokenize.DEDENT,
        ):
            continue
        elif tok.type == tokenize.ENDMARKER:
            break
        else:
            if pending:
                blocks[tok.start[0]] = " ".join(pending)
                pending = []
    return blocks


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    ru = root / "src" / "binaural" / "locales" / "ru.py"
    out_path = root / "apple" / "Sources" / "Core" / "Locales" / "RussianCatalogue.swift"

    source = ru.read_text(encoding="utf-8")
    messages = messages_node(ast.parse(source))
    blocks = comments_by_line(source)

    entries: list[tuple[str, str, str | None]] = []
    seen: set[str] = set()
    for key_node, value_node in zip(messages.keys, messages.values):
        assert isinstance(key_node, ast.Constant), ast.dump(key_node)
        assert isinstance(value_node, ast.Constant), ast.dump(value_node)
        key = key_node.value
        if key in seen:
            raise SystemExit(f"duplicate key in ru.py: {key!r}")
        seen.add(key)
        entries.append((key, value_node.value, blocks.get(key_node.lineno)))

    out = io.StringIO()
    out.write(HEADER)
    current: str | None = None
    for key, value, comment in entries:
        if comment and comment != current:
            if current is not None:
                out.write("\n")
            out.write(f"        // {comment}\n")
            current = comment
        out.write(f"        {swift_literal(key)}: {swift_literal(value)},\n")
    out.write("    ]\n}\n")

    # A key in both files would be a merge order nobody decided on: `ru.py` owns it, and
    # the hand-written copy in `RussianWindowAdditions` has to go. Checked before writing,
    # so a stale additions file is refused rather than silently shadowed.
    additions_path = out_path.with_name("RussianWindowAdditions.swift")
    duplicates = [
        key for key in swift_keys(in_additions(additions_path.read_text(encoding="utf-8")))
        if key in seen
    ]
    if duplicates:
        raise SystemExit(
            "keys in both ru.py and RussianWindowAdditions.swift: "
            + ", ".join(repr(key) for key in sorted(duplicates))
            + " — delete the hand-written copy"
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out.getvalue(), encoding="utf-8")
    print(f"{out_path.relative_to(root)}: {len(entries)} keys", file=sys.stderr)


if __name__ == "__main__":
    main()