"""Regenerate the Swift Russian catalogue from the Python one.

    python3 apple/Tools/generate_russian_catalogue.py

`src/binaural/locales/ru.py` is the single source of truth for Russian text
(CONTRACT rule 3). This script parses it with the Python AST — so implicit
string concatenation is resolved exactly the way `i18n.tr` sees it — and writes
`apple/Sources/Core/Locales/RussianCatalogue.swift` with the same keys, the same
order and the same section comments.

It reads the Python package and writes only into `apple/`.
"""

from __future__ import annotations

import ast
import io
import sys
import tokenize
from pathlib import Path

HEADER = '''import Foundation

/// The Russian catalogue: English source string -> Russian text.
///
/// Verbatim port of `src/binaural/locales/ru.py` (`MESSAGES`). The keys are the
/// English source strings exactly as they are passed to ``L10n/tr(_:_:)``, which is
/// what makes a missing key degrade to English instead of to an empty label.
///
/// Generated by `apple/Tools/generate_russian_catalogue.py` from the Python AST
/// (implicit string concatenation already resolved by the parser) and ordered like
/// the Python dictionary, section comments included. `L10nTests` asserts the key
/// count and that every key the app references is present, so this file cannot
/// quietly drift away from `ru.py`.
///
/// Style follows `ru.py`: calm and factual, no marketing and no medical promises
/// (SPEC §6.13 - the app is not a medical device). Placeholders (`%1`, `{name}`) are
/// kept verbatim: only the surrounding wording is translated.
public enum RussianCatalogue {

    /// Every Russian message, keyed by its English source string.
    public static let messages: [String: String] = [
'''


def swift_literal(text: str) -> str:
    out = ['"']
    for ch in text:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def messages_node(tree: ast.AST) -> ast.Dict:
    """The `MESSAGES` dict literal of the catalogue module."""
    for node in ast.walk(tree):
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", "") == "MESSAGES":
            assert isinstance(node.value, ast.Dict)
            return node.value
    raise SystemExit("MESSAGES not found")


def comments_by_line(source: str) -> dict[int, str]:
    """The comment block that documents the first code token after it."""
    blocks: dict[int, str] = {}
    pending: list[str] = []
    for tok in tokenize.generate_tokens(io.StringIO(source).readline):
        if tok.type == tokenize.COMMENT:
            body = tok.string.lstrip("#").strip()
            if not body:
                pending = []
            elif body.startswith("---") and body.endswith("---"):
                # A section header: the dashes are decoration, the text is the title.
                pending = [body.strip("- ").strip()]
            else:
                pending.append(body)
        elif tok.type in (
            tokenize.NL,
            tokenize.NEWLINE,
            tokenize.INDENT,
            tokenize.DEDENT,
        ):
            continue
        elif tok.type == tokenize.ENDMARKER:
            break
        else:
            if pending:
                blocks[tok.start[0]] = " ".join(pending)
                pending = []
    return blocks


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    ru = root / "src" / "binaural" / "locales" / "ru.py"
    out_path = root / "apple" / "Sources" / "Core" / "Locales" / "RussianCatalogue.swift"

    source = ru.read_text(encoding="utf-8")
    messages = messages_node(ast.parse(source))
    blocks = comments_by_line(source)

    entries: list[tuple[str, str, str | None]] = []
    seen: set[str] = set()
    for key_node, value_node in zip(messages.keys, messages.values):
        assert isinstance(key_node, ast.Constant), ast.dump(key_node)
        assert isinstance(value_node, ast.Constant), ast.dump(value_node)
        key = key_node.value
        if key in seen:
            raise SystemExit(f"duplicate key in ru.py: {key!r}")
        seen.add(key)
        entries.append((key, value_node.value, blocks.get(key_node.lineno)))

    out = io.StringIO()
    out.write(HEADER)
    current: str | None = None
    for key, value, comment in entries:
        if comment and comment != current:
            if current is not None:
                out.write("\n")
            out.write(f"        // {comment}\n")
            current = comment
        out.write(f"        {swift_literal(key)}: {swift_literal(value)},\n")
    out.write("    ]\n}\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out.getvalue(), encoding="utf-8")
    print(f"{out_path.relative_to(root)}: {len(entries)} keys", file=sys.stderr)


if __name__ == "__main__":
    main()