# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Binaural.

Build:

    pyinstaller packaging/pyinstaller.spec

Why one-dir and not one-file:
    the release archive ships a whole directory anyway, one-dir starts faster, and the
    unpacked layout is inspectable when something goes wrong on a user's machine.

Why QtMultimedia is listed explicitly:
    Qt's audio backend is a *runtime plugin*, not an import. PyInstaller's static
    analysis sees `from PySide6.QtMultimedia import QAudioSink` and sees nothing about
    the ffmpeg/AVFoundation backend underneath it, so the frozen app starts and then
    fails with "no audio device / no multimedia backend". Collecting QtMultimedia and
    pointing QT_PLUGIN_PATH at the real plugins directory is what actually fixes it.
"""

import os
import sys
from pathlib import Path

# --------------------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------------------

# SPECPATH is injected by PyInstaller: the directory holding this .spec file.
SPEC_DIR = Path(SPECPATH).resolve()
ROOT = SPEC_DIR.parent
SRC = ROOT / "src"
PKG = SRC / "binaural"
DATA_DIR = PKG / "data"

# The spec itself is platform-agnostic: scripts/build_linux.sh and scripts/build_macos.sh
# both build with it. macOS also ships the native Swift app (apple/); the Python archive
# is what `curl | sh` downloads there. There is no Info.plist and no .icns: nothing in
# this spec builds a branded .app.
LINUX_DIR = SPEC_DIR / "linux"

# PyInstaller cannot use src/binaural/app.py as the entry script directly: it runs the
# file as __main__, so the relative imports inside it ("from .ui.main_window import ...")
# fail with "attempted relative import with no known parent package". The fix is a
# one-line launcher that imports the package properly. It is generated here rather than
# committed so there is exactly one entry point definition (app.main) and no extra file
# to keep in sync.
LAUNCHER_DIR = ROOT / "build" / "launcher"
LAUNCHER = LAUNCHER_DIR / "binaural_launcher.py"
LAUNCHER_DIR.mkdir(parents=True, exist_ok=True)
LAUNCHER.write_text(
    '"""Generated by packaging/pyinstaller.spec — do not edit."""\n'
    "import multiprocessing\n"
    "import sys\n"
    "\n"
    "from binaural.app import main\n"
    "\n"
    "if __name__ == '__main__':\n"
    "    multiprocessing.freeze_support()\n"
    "    sys.exit(main())\n",
    encoding="utf-8",
)

APP_NAME = "Binaural"
# The console script is `binaural` (lowercase, matches pyproject [project.scripts]),
# and the one-dir bundle folder is `Binaural`.
EXE_NAME = "binaural"

# --------------------------------------------------------------------------------------
# Qt: make sure the multimedia backend and the plugins get collected
# --------------------------------------------------------------------------------------

# The PySide6 hooks read QT_PLUGIN_PATH to decide which plugin folders to bundle. Setting
# it to the real plugins directory keeps the full set, and the analysis below adds the
# data files explicitly as well, in case the hook is bypassed.
_pyside6_root = None
try:
    import PySide6  # noqa: F401  (imported for its location only)

    _pyside6_root = Path(PySide6.__file__).resolve().parent
except Exception:  # pragma: no cover - only hit on a broken venv
    pass

qt_datas = []
qt_binaries = []
qt_hiddenimports = []

if _pyside6_root is not None:
    os.environ["QT_PLUGIN_PATH"] = str(_pyside6_root / "plugins")

    try:
        from PyInstaller.utils.hooks import collect_all

        for _mod in ("PySide6.QtMultimedia", "PySide6.QtMultimediaWidgets"):
            try:
                _d, _b, _h = collect_all(_mod)
            except Exception:
                continue
            qt_datas += _d
            qt_binaries += _b
            qt_hiddenimports += _h
    except Exception:  # pragma: no cover
        pass

    # Every Qt plugin folder, plus the libraries Qt dlopen()s by name at runtime.
    _plugins = _pyside6_root / "plugins"
    if _plugins.is_dir():
        for _entry in sorted(_plugins.iterdir()):
            if _entry.is_dir():
                qt_datas.append((str(_entry), f"PySide6/plugins/{_entry.name}"))
            else:
                qt_binaries.append((str(_entry), f"PySide6/plugins/{_entry.name}"))

# QtMultimedia pulls its backend through dlopen, so the name has to be listed even
# though nothing in our code imports these modules.
qt_hiddenimports += [
    "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets",
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "PySide6.QtNetwork",
]

# --------------------------------------------------------------------------------------
# Application data
# --------------------------------------------------------------------------------------

datas = list(qt_datas)

# frequencies.json and any future .json in the data package (SPEC §6.2). It must land
# next to binaural/data/frequencies.py inside the bundle so `Path(__file__).parent` finds it.
if DATA_DIR.is_dir():
    for _json in sorted(DATA_DIR.glob("*.json")):
        datas.append((str(_json), "binaural/data"))

# Linux desktop integration: the .desktop file and the icon travel with the binary so
# build_linux.sh only has to tar the folder it gets.
_DESKTOP = LINUX_DIR / "binaural.desktop"
if _DESKTOP.is_file():
    datas.append((str(_DESKTOP), "share/applications"))

for _icon_name, _icon_subdir in (
    ("binaural.svg", "share/icons/hicolor/scalable/apps"),
    ("binaural.png", "share/icons/hicolor/256x256/apps"),
    ("binaural.png", "share/pixmaps"),
):
    _icon = LINUX_DIR / _icon_name
    if _icon.is_file():
        datas.append((str(_icon), _icon_subdir))
        break

# --------------------------------------------------------------------------------------
# Analysis
# --------------------------------------------------------------------------------------

# Our own package is not installed in the build environment necessarily, and the audio
# backends are chosen at runtime by a factory (audio/platform/__init__.py), so static
# analysis cannot see them. Hidden-import the whole package.
try:
    from PyInstaller.utils.hooks import collect_submodules

    # SRC must be importable *before* the collection runs, otherwise
    # collect_submodules silently returns [] (it does not raise) and every
    # dynamically imported module — binaural.locales.ru is one — is dropped
    # from the bundle. Insert unconditionally, not in the except branch.
    sys.path.insert(0, str(SRC))
    binaural_hiddenimports = collect_submodules("binaural")
    if not binaural_hiddenimports:
        # Belt and braces: the catalogue is imported through
        # importlib.import_module(), which static analysis cannot follow.
        binaural_hiddenimports = [
            "binaural.locales",
            "binaural.locales.ru",
        ]
except Exception:  # pragma: no cover
    sys.path.insert(0, str(SRC))
    binaural_hiddenimports = ["binaural.locales", "binaural.locales.ru"]

hiddenimports = list(qt_hiddenimports) + list(binaural_hiddenimports)

# Everything the app never touches. numpy/scipy are test-time only (pyproject [dev]),
# and the Qt WebEngine / Quick / 3D stacks are megabytes of dead weight.
excludes = [
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "pytest",
    "_pytest",
    "IPython",
    "tkinter",
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebEngineQuick",
    "PySide6.QtQuick",
    "PySide6.QtQuick3D",
    "PySide6.Qt3DCore",
    "PySide6.QtCharts",
    "PySide6.QtDataVisualization",
    "PySide6.QtBluetooth",
    "PySide6.QtPositioning",
    "PySide6.QtSql",
    "PySide6.QtTest",
    "PySide6.QtDesigner",
    "PySide6.QtHelp",
    "distutils",
]

# Never bundle the build virtualenv.
for _noise in (".venv", "venv", "build", "dist", ".git", "tests"):
    excludes.append(_noise)

a = Analysis(
    [str(LAUNCHER)],
    pathex=[str(SRC)],
    binaries=list(qt_binaries),
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

# --------------------------------------------------------------------------------------
# Executable
# --------------------------------------------------------------------------------------

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=EXE_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name=APP_NAME,
)
